-- courses
create table courses (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  level text,
  fee numeric(10,2),
  short_desc text,
  cover_url text,
  created_at timestamptz default now()
);

-- batches
create table batches (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id) on delete cascade,
  start_date date,
  end_date date,
  timing text,          -- e.g. "Mon-Fri 7-9 AM"
  mode text,            -- Online / Offline
  seats int,
  fee_override numeric(10,2)
);

-- enrollments with pay-status
create type enrollment_status as enum ('PENDING','PAID','CANCELLED');
create table enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  batch_id bigint references batches(id),
  status enrollment_status default 'PENDING',
  payment_id text,
  enrolled_at timestamptz default now()
);

-- flashcards & SM-2 progress
create table flashcards (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id),
  front text,
  back text
);

create table user_flashcard_progress (
  user_id uuid references auth.users(id),
  card_id bigint references flashcards(id),
  interval int default 0,
  repetition int default 0,
  ease float default 2.5,
  due_date date default current_date,
  primary key (user_id, card_id)
);

-- quizzes & PYQs
create table quizzes (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id),
  title text,
  duration int   -- minutes
);

create table questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint references quizzes(id),
  stem text,
  options jsonb,
  answer int
);

create table attempts (
  id bigint generated by default as identity primary key,
  quiz_id bigint references quizzes(id),
  user_id uuid references auth.users(id),
  score int,
  started_at timestamptz,
  ended_at timestamptz
);
